import type { NextPage } from "next";
import Head from "next/head";
import BoxShadowPageComponent from "../../PageComponents/Components/BoxShadow/BoxShadowPage";
import { Page } from "../../styles/globals";

const BoxShadow: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Box Shadow Tests - Jaco Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <BoxShadowPageComponent />
      </Page>
    </div>
  );
};

export default BoxShadow;
